# Ini adalah format TOML yang benar

OPENAI_API_KEY = "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"

GOOGLE_API_KEY = "AIzaSyChZ94xDDTEQLQw2oI7vSa6qCvgV-L9FCM"

SEARCH_ENGINE_ID = "81a59577e42a44b53"
